// Code generated by MockGen. DO NOT EDIT.
// Source: forms.go
//
// Generated by this command:
//
//	mockgen -source forms.go -destination mock_test.go -package forms -typed
//

// Package forms is a generated GoMock package.
package forms

import (
	reflect "reflect"

	survey "github.com/AlecAivazis/survey/v2"
	gomock "go.uber.org/mock/gomock"
)

// Mocksurveyor is a mock of surveyor interface.
type Mocksurveyor struct {
	ctrl     *gomock.Controller
	recorder *MocksurveyorMockRecorder
	isgomock struct{}
}

// MocksurveyorMockRecorder is the mock recorder for Mocksurveyor.
type MocksurveyorMockRecorder struct {
	mock *Mocksurveyor
}

// NewMocksurveyor creates a new mock instance.
func NewMocksurveyor(ctrl *gomock.Controller) *Mocksurveyor {
	mock := &Mocksurveyor{ctrl: ctrl}
	mock.recorder = &MocksurveyorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksurveyor) EXPECT() *MocksurveyorMockRecorder {
	return m.recorder
}

// AskOne mocks base method.
func (m *Mocksurveyor) AskOne(p survey.Prompt, response any, opts ...survey.AskOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{p, response}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AskOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AskOne indicates an expected call of AskOne.
func (mr *MocksurveyorMockRecorder) AskOne(p, response any, opts ...any) *MocksurveyorAskOneCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{p, response}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskOne", reflect.TypeOf((*Mocksurveyor)(nil).AskOne), varargs...)
	return &MocksurveyorAskOneCall{Call: call}
}

// MocksurveyorAskOneCall wrap *gomock.Call
type MocksurveyorAskOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksurveyorAskOneCall) Return(arg0 error) *MocksurveyorAskOneCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksurveyorAskOneCall) Do(f func(survey.Prompt, any, ...survey.AskOpt) error) *MocksurveyorAskOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksurveyorAskOneCall) DoAndReturn(f func(survey.Prompt, any, ...survey.AskOpt) error) *MocksurveyorAskOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
